services:
  postgres:
    container_name: fundamentos-backend-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nestdb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  api:
    build: .
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/nestdb

